### ISSUE TITLE
pycapnp build failed (Cython==0.22)

### ISSUE THREAD

**Issue by dreamTown** [jparyani/pycapnp#63]
Hi, I want to install pycapnp to then install nupic, and I've been stuck with one error for a while now:

/private/var/folders/cq/hfzg1bwx4gqbxn2pd0r0553r0000gr/T/pip-build-6GgSd3/pycapnp/build/include/kj/common.h:54:8: warning: "Your compiler supports C++11 but your C++ standard library does not.  If your "               "system has libc++ installed (as should be the case on e.g. Mac OSX), try adding "               "-stdlib=libc++ to your CXXFLAGS." [-W#warnings]
          #warning "Your compiler supports C++11 but your C++ standard library does not.  If your "\
           ^
    /private/var/folders/cq/hfzg1bwx4gqbxn2pd0r0553r0000gr/T/pip-build-6GgSd3/pycapnp/build/include/kj/common.h:78:10: fatal error: 'initializer_list' file not found
    #include <initializer_list>
             ^
    2 warnings and 1 error generated.
    error: command 'gcc' failed with exit status 1

I run on Mac OS 10.10 and I have the latest Xcode and clang version. I did install a homebrew version of gcc 4.9.2 and it worked, but unfortunately nupic doesn't compile with gcc 4.9. However I noticed that the requirements are Cython==0.21.2 and I have 0.22 distributed with anaconda 2.2.0. Could it be the reason for the issue ? 

Many thanks.

**Comment by jparyani** [comment]
Can you try running:
```bash
export CXXFLAGS="-stdlib=libc++"
export CFLAGS="-stdlib=libc++"
```

In the shell before installing pycapnp?

**Comment by dreamTown** [comment]
It didn't worked, but thanks to recommandations on the nupic thread I tried:

export MACOSX_DEPLOYMENT_TARGET=10.10

and everything was successfully installed !!

Thanks.

**Comment by jparyani** [comment]
Great, glad you got it sorted out.

**Comment by mingkin** [comment]
its work      export MACOSX_DEPLOYMENT_TARGET=10.10

**Comment by KashyapKishore** [comment]
worked with export MACOSX_DEPLOYMENT_TARGET=10.10 before running 'pip install pycapnp' on MacOS Mojave
